HW3 ex. 1-3
fedir-n/prjctr-js pull request #5
Opened 2024-04-20 15:10 UTC by fedir-n

1. Задача про ітерацію

Напишіть функцію яка ітеративно (в циклі) буде знаходити суму всіх непарних додатніх чисел до якогось числа.

Приклад:

function iterativeOddSumTo(number) {

// тут ваш код

};

console.log(iterativeOddSumTo(1)) // 1
console.log(iterativeOddSumTo(9)) // 25
console.log(iterativeOddSumTo(10)) // 25

2. Задача про рекурсію 

Напишіть функцію яка рекурсивно буде знаходити суму всіх непарних додатніх чисел до якогось числа.

Приклад:

function recursiveOddSumTo(number) {

// тут ваш код

};

console.log(recursiveOddSumTo(1)) // 1
console.log(recursiveOddSumTo(9)) // 25
console.log(recursiveOddSumTo(10)) // 25

3. Додаткова задача*

Напишіть стрілочну функцію isXOEqual яка перевіряє чи рядок має однакову кількість символів «x» та «o». Функція повинна повертати логічне значення та бути нечутливою до регістру. Рядок може містити будь-які символи.

2024-04-21 16:32 UTC, myroslav-kolomiiets requested changes

2024-04-21 16:32 UTC, myroslav-kolomiiets commented on homeworks.js
> +//////////////////////////////////
Видали всі лишні рядки і подібне. Приведи файл з роботою до нормального вигляду.

2024-04-21 16:32 UTC, myroslav-kolomiiets commented on homeworks.js
> +    // chatGPT solution
А навіщо тут та в інших місцях "chatGPT solution"?)

2024-04-21 16:32 UTC, myroslav-kolomiiets commented on homeworks.js
> +    countSymbolOne = arr.filter(x => x ==='x').length;
Хвалю, що використовуєш те, що ми ще не проходили, головне, щоб розумів що і до чого)

2024-04-21 16:32 UTC, myroslav-kolomiiets commented on homeworks.js
> +
Навіщо в файлі така кількість пустих рядків на початку?

Де 'use strict'; ?

2024-04-21 16:32 UTC, myroslav-kolomiiets commented on homeworks.js
> +    countSymbolOne = arr.filter(x => x ==='x').length;
І головне, в строгому режимі на цьому рядку скрипт впаде з помилкою.

2024-04-21 16:32 UTC, myroslav-kolomiiets commented on homeworks.js
> +    countSymbolOne = arr.filter(x => x === String(symbolOne)).length;
Як ми об'являємо змінні?)

2024-04-22 12:50 UTC, fedir-n commented on homeworks.js
> +    countSymbolOne = arr.filter(x => x === String(symbolOne)).length;
> Як ми об'являємо змінні?)

Не так, як я звик робити це в пайтоні))

2024-04-24 18:27 UTC, myroslav-kolomiiets requested changes

2024-04-25 06:13 UTC, fedir-n commented on HW3/homework3.js
> +const isSymbolsEqual = (str, symbolOne, symbolTwo) => {
Імпрувмент дозволяє передати в функцію і порівняти кількість будь-яких символів, а не тільки 'x','o'

2024-04-25 18:19 UTC, merged